# Generated by Django 3.1.4 on 2020-12-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20201223_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_type', models.CharField(choices=[(1, 'Access'), (2, 'Deny')], max_length=2, verbose_name='Sharing Type')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_file', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharing File',
                'verbose_name_plural': 'Sharing File',
            },
        ),
        migrations.DeleteModel(
            name='Share_access',
        ),
    ]
