# Generated by Django 3.1.4 on 2020-12-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201223_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharingtasks',
            name='sharing_type',
            field=models.IntegerField(choices=[(1, 'Access'), (2, 'Deny')], verbose_name='Sharing Type'),
        ),
    ]
