# Generated by Django 3.1.4 on 2020-12-23 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201223_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharingTasks',
            new_name='SharingFile',
        ),
    ]
