# Generated by Django 3.1.4 on 2020-12-24 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20201223_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingfile',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_title', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharingfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
